### ISSUE TITLE
pod/my-hami-webui-dcgm-exporter indicates "Failed to watch metrics: Error watching fields: The third-party Profiling module returned an unrecoverable error"

### ISSUE THREAD

**Issue by jiangsanyin** [Project-HAMi/HAMi-WebUI#20]
1）k8s环境
root@controller01:~# kubectl get nodes
NAME          STATUS   ROLES    AGE   VERSION
172.20.0.21   Ready    master   12d   v1.23.17

2）HAMi环境
root@controller01:~# helm -n kube-system list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
hami            kube-system     2               2025-01-14 11:22:08.530587544 +0800 CST deployed        hami-2.4.1              2.4.1      
my-hami-webui   kube-system     1               2025-01-22 14:46:54.779441278 +0800 CST deployed        hami-webui-1.0.3        1.0.3 

3）Prometheus版本
2.36.1 

4）Helm版本
root@controller01:~# helm version
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

5）NVIDIA GPU
![Image](https://github.com/user-attachments/assets/6d52c8f1-9f2b-41b1-9ffa-2491e7ab3424)

6）安装hami-webui
#1.添加HAMi-WebUI repository
helm repo add hami-webui https://project-hami.github.io/HAMi-WebUI
#2.使用helm部署HAMi-WebUI（其中externalPrometheus.address参数的值以k8s环境中prometheus实际服务名为准，端口一般都是9090）
helm install my-hami-webui hami-webui/hami-webui --set externalPrometheus.enabled=true --set externalPrometheus.address="http://prometheus-k8s.monitoring.svc.cluster.local:9090" -n kube-system

7）pod/my-hami-webui-dcgm-exporter-5whhm 一直处于CrashLoopBackOff   状态
root@controller01:~# kubectl -n kube-system get pods -l app.kubernetes.io/instance=my-hami-webui
NAME                                READY   STATUS             RESTARTS        AGE
my-hami-webui-c6f4b6c98-q9vfc       2/2     Running            0               39m
my-hami-webui-dcgm-exporter-5whhm   0/1     CrashLoopBackOff   6 (3m29s ago)   9m30s
其中my-hami-webui-dcgm-exporter使用的镜像是“nvcr.io/nvidia/k8s/dcgm-exporter:3.3.7-3.5.0-ubuntu22.04”

8）pod/my-hami-webui-dcgm-exporter-5whhm 日志
root@controller01:~# kubectl -n kube-system logs my-hami-webui-dcgm-exporter-5whhm 
2025/01/22 07:22:31 maxprocs: Leaving GOMAXPROCS=64: CPU quota undefined
time="2025-01-22T07:22:31Z" level=info msg="Starting dcgm-exporter"
time="2025-01-22T07:22:31Z" level=info msg="DCGM successfully initialized!"
time="2025-01-22T07:22:31Z" level=info msg="Collecting DCP Metrics"
time="2025-01-22T07:22:31Z" level=info msg="Falling back to metric file '/etc/dcgm-exporter/dcp-metrics-included.csv'"
time="2025-01-22T07:22:31Z" level=info msg="Initializing system entities of type: GPU"
time="2025-01-22T07:22:31Z" level=info msg="Not collecting NvSwitch metrics; no fields to watch for device type: 3"
time="2025-01-22T07:22:31Z" level=info msg="Not collecting NvLink metrics; no fields to watch for device type: 6"
time="2025-01-22T07:22:31Z" level=info msg="Not collecting CPU metrics; no fields to watch for device type: 7"
time="2025-01-22T07:22:31Z" level=info msg="Not collecting CPU Core metrics; no fields to watch for device type: 8"
time="2025-01-22T07:22:31Z" level=fatal msg="Failed to watch metrics: Error watching fields: The third-party Profiling module returned an unrecoverable error"

请问，为何会出现此问题？如何解决？

**Comment by jiangsanyin** [comment]
1）这里有一个同样的问题“https://forums.developer.nvidia.com/t/dcgm-exporter-3-6-0-can-not-gather-metrics-from-the-ga100-gpu-a100-80gb/315043”，但没有回复
2）这里有个类似的问题"https://github.com/NVIDIA/dcgm-exporter/issues/148"，但具体报错信息不同。此问题中是因为“NVIDIA GPU GSP feature”引起的，但我的问题中没有GSP 相关字样

**Comment by jiangsanyin** [comment]
#修改daemonsets/my-hami-webui-dcgm-exporter，将参数“args: -f /etc/dcgm-exporter/dcp-metrics-inclueded.csv”去掉
root@controller01:~# kubectl -n kube-system edit daemonsets.apps my-hami-webui-dcgm-exporter 

然后可行了。目前没发现什么问题

**Comment by chenyg0911** [comment]
update daemonset, pod run normal. All update lines marked as **<=Add** 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
......
spec:
......
  template:
    metadata:
      annotations:
        hami.io/webhook: ignore   ####### <= Add
        scheduling.k8s.io/group-name: ignore ####### <=Add
   ...
    spec:
      containers:
      - args:
        - -f
        - /etc/dcgm-exporter/dcp-metrics-included.csv
        env:
        - name: NVIDIA_VISIBLE_DEVICES ####### <=Add
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES ####### <=Add
          value: compute,utility,compat32
        - name: DCGM_EXPORTER_KUBERNETES
          value: "true"
        - name: DCGM_EXPORTER_LISTEN
          value: :9400
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: nvcr.io/nvidia/k8s/dcgm-exporter:3.3.7-3.5.0-ubuntu22.04
        imagePullPolicy: IfNotPresent
       resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true ####### <=Add
          runAsNonRoot: false
          runAsUser: 0
      runtimeClassName: nvidia ####### <=Add
      schedulerName: default-scheduler
...
```
